<?xml version="1.0"?>
<robot name="koubot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="robot_name" value="koubot"/>

    <xacro:property name="chassis_mass" value="5.0"/>
    <xacro:property name="chassis_width" value="0.155"/>
    <xacro:property name="chassis_depth" value="0.2"/>
    <xacro:property name="chassis_height" value="0.11"/>

    <xacro:property name="wheel_mass" value="0.5"/>
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_length" value="0.036"/>
    <xacro:property name="wheel_offset_x" value="0.05"/>
    <xacro:property name="wheel_offset_y" value="0.114"/>
    <xacro:property name="wheel_offset_z" value="0.04"/>

    <xacro:property name="M_PI" value="3.141592654"/>

    <!--Inertia Calculator for Chassis-->
    <xacro:macro name="chassis_inertia" params="mass_chassis x y z">
        <inertia  ixx="${mass_chassis*(y*y+z*z)/12.0}" ixy = "0" ixz = "0"
              iyy="${mass_chassis*(x*x+z*z)/12.0}" iyz = "0"
              izz="${mass_chassis*(x*x+y*y)/12.0}"
        />
    </xacro:macro>

    <!--Inertia Calculator for Wheels-->
    <xacro:macro name="wheels_inertia" params="mass_wheel r h">
        <inertia  ixx="${mass_wheel*(3*r*r + h*h)/12.0}" ixy = "0" ixz = "0"
              iyy="${mass_wheel*(3*r*r + h*h)/12.0}" iyz = "0"
              izz="${mass_wheel*(r*r)/2.0}"
        />
    </xacro:macro>

    <!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% FRICTION & STIFNESS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->

    <!--

    mu1: The static friction coefficient. 
    It is how much friction there is until the object starts moving in simple terms.

    mu2: The dynamic friction coefficient. 
    It is how much friction there is when the object moves in simple terms. 
    
    kp: This coefficient sets the static contact stiffness. 
    This determines whether the linked material is closer to marble (rigid, bigger values) 
    or more like rubber (soft material, lower values).

    kd: This coefficient sets the dynamic contact stiffness. 
    This determines whether the linked material is closer to marble (rigid, bigger values) 
    or more like rubber (soft material, lower values). 
    It is essentially how much it deforms over a long period, exerting its pressure.

    -->

    <!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-->
    <!-- BASE FOOTPRINT -->
    <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.0001 0.0001 0.0001" />
            </geometry>
        </visual>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0.081" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>

<!-- BASE LINK -->
    <link name="base_link">
        <inertial>
            <mass value="${chassis_mass}" />
            <origin xyz="0 0 0.0" />
            <xacro:chassis_inertia mass_chassis="${chassis_mass}" x="${chassis_depth}" y="${chassis_width}" z="${chassis_height}"/>
        </inertial>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
            <geometry>
                <box size="${chassis_width} ${chassis_depth} ${chassis_height}" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 -${chassis_height/2}" rpy="-${M_PI/2} 0 0" />
            <geometry>
                <mesh filename="package://robot_description/meshes/chassis.dae"/>
            </geometry>
        </visual>
    </link>

    <!-- Joint - base_link / front left wheel -->
    <joint name="joint_base_link_front_left_wheel" type="continuous">
        <origin rpy="0 0 0" xyz="${wheel_offset_x} ${wheel_offset_y} -${wheel_offset_z}" />
        <child link="front_left_wheel" />
        <parent link="base_link" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="1.0" />
    </joint>

    <!-- FRONT LEFT WHEEL -->
    <link name="front_left_wheel">
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <xacro:wheels_inertia mass_wheel="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </inertial>

        <collision>
            <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="${M_PI} 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://robot_description/meshes/wheels.dae"/>
            </geometry>
        </visual>
    </link>

    <!-- Joint - base_link / front right wheel -->
    <joint name="joint_base_link_front_right_wheel" type="continuous">
        <origin rpy="0 0 0" xyz="${wheel_offset_x} -${wheel_offset_y} -${wheel_offset_z}" />
        <child link="front_right_wheel" />
        <parent link="base_link" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="1.0" />
    </joint>

    <!-- FRONT RIGHT WHEEL -->
    <link name="front_right_wheel">
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <xacro:wheels_inertia mass_wheel="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </inertial>

        <collision>
            <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="${M_PI} 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://robot_description/meshes/wheels.dae"/>
            </geometry>
        </visual>
    </link>

    <!-- Joint - base_link / back right wheel -->
    <joint name="joint_base_link_back_right_wheel" type="continuous">
        <origin rpy="0 0 0" xyz="-${wheel_offset_x} -${wheel_offset_y} -${wheel_offset_z}" />
        <child link="back_right_wheel" />
        <parent link="base_link" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="1.0" />
    </joint>

    <!-- BACK RIGHT WHEEL -->
    <link name="back_right_wheel">
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <xacro:wheels_inertia mass_wheel="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </inertial>

        <collision>
            <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="${M_PI} 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://robot_description/meshes/wheels.dae"/>
            </geometry>
        </visual>
    </link>

    <!-- Joint - base_link / back left wheel -->
    <joint name="joint_base_link_back_left_wheel" type="continuous">
        <origin rpy="0 0 0" xyz="-${wheel_offset_x} ${wheel_offset_y} -${wheel_offset_z}" />
        <child link="back_left_wheel" />
        <parent link="base_link" />
        <axis rpy="0 0 0" xyz="0 1 0" />
        <limit effort="10000" velocity="1000" />
        <joint_properties damping="1.0" friction="1.0" />
    </joint>

    <!-- BACK LEFT WHEEL -->
    <link name="back_left_wheel">
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <xacro:wheels_inertia mass_wheel="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </inertial>

        <collision>
            <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="${M_PI} 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://robot_description/meshes/wheels.dae"/>
            </geometry>
        </visual>
    </link>


    <!-- FRONT LASER -->
    <!-- <link name="front_laser">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>

    <joint name="front_laser_joint" type="fixed">
        <origin xyz="0.65 0 0.075" rpy="3.14159265359 0 0" />
        <parent link="base_link"/>
        <child link="front_laser" />
    </joint> -->

    <xacro:include filename="$(find robot_description)/urdf/base/koubot_base.gazebo" />

</robot>